techno-tim/k3s-ansible

roles/raspberrypi/tasks/main.yml, roles/raspberrypi/tasks/prereq/Raspbian.yml
Fixes issue with Debian Bullseye on raspberry pi not being detected. So it does no run the Raspbian tasks.
Also added install of iptables if this dependency is missing.
On Debian Buster its installed as default but not on Debian Bullseye.
I have tested it on both Debian Buster and Debian Bullseye
=> Fixed issue with tasks not running on Debian Bullseye

.gitignore, README.md, roles/k3s/master/tasks/main.yml, vagrant/Vagrantfile
I've added a Vagrantfile to the vagrant subdirectory. One may create a working environment by the command `vagrant up` and run the Ansible playbook by the command `vagrant provision --provision-with ansible`.
I also added a section within the README.md regarding the usage of Vagrant and I made the retry_count in the `Verification` section of the master role customizeable (default is still 20).
I made the experience, that the `ubuntu2110` Box Image of Vagrant is not running into a VirtualBox issue so often than other Ubuntu images do. It still happens from time to time, making the VM unresponsive. It is described [here](https://forums.virtualbox.org/viewtopic.php?f=6&t=105047).
=> Added Vagrantfile for build environment with Vagrant

inventory/sample/group_vars/all.yml, roles/prereq/tasks/main.yml
Hello Tim
I'm a swiss systemengineer who likes your content, I was accually also writing my own k3s ansible playbooks in the last week, but it is not as extensive as your forked one. I do this pull request only for learning, but if you like the change you can test it and merge. I do not need it working like that, cause I want to finish my own playbook. But maby this change saves someone who uses AlmaLinux or Rocky some time.
Attention: These changes are 100% untested, but it should work like that.
Kind Regards
~Janic 
I replaced the matching distributions from centos and redhat to matching os family (Redhat) cause this includes also some addtional distributions.
=> Using Ansible os family instead of multiple Ansible os distributions

roles/k3s/master/tasks/main.yml
I found on v1.24.2+k3s2 any manifest files that had a double extension foo.bar.yaml would not get picked up. I was alerted to this by Kube-VIP not starting due to a missing service account and role binding. Changing the '.' to '-' fixed the issue. I have also run this on the previous K3s to ensure it still works.
- [ X] Tested locally
- [X ] Ran `site.yml` playbook
- [ X] Ran `reset.yml` playbook
- [X ] Did not add any unnecessary changes
=> Replaced manifest files with double extention to '-'

inventory/.gitignore
- The `.gitignore` file under `inventory/` would still ignore the `sample` folder (even though line 3 suggests otherwise). This patch fixes that so that the file works as intended (or at least as I believe it was intended) :-). For more details, see: https://stackoverflow.com/a/20652768
=> Fix .gitignore

inventory/sample/group_vars/all.yml
According to [Kubernetes Components](https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#kubernetes-components) section the `--disable <value>` flag should  instead of `--no-deploy <value>` as the latter is listed under [Deprecated Options](https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#deprecated-options)
- Edited `inventory/sample/group_vars/all.yml` by replacing `--no-deploy <value>` with `--disable <value>`
- [ x ] Tested locally
- [ x ] Ran `site.yml` playbook
- [ x ] Ran `reset.yml` playbook
- [ x ] Did not add any unnecessary changes
- [ x ] 🚀
=> Replace deprecated flag --no-deploy with --disable

roles/raspberrypi/tasks/prereq/Ubuntu.yml, roles/reset/tasks/main.yml
Ubuntu 22.x on Raspberry Pi needs the linux-modules-extra-raspi package
for the vxlans kernel module.
K3S on Ubuntu 22.x requires the linux-modules-extra-raspi package for the vxlan kernel module.
NOTE: Not sure if we want to force removal of the linux-modules-extra-raspi package during reset, but included it anyway.
=> Add linux-modules-extra-raspi package for Ubuntu 22.x on Raspberry.

roles/k3s/master/tasks/main.yml
This fixes an "issue" that causes manifests to be reapplied each time the k3s service is started.  This will remove the contents of `/var/lib/rancher/k3s/server/manifests` after the cluster has applied the files.
[k3s advanced docs](https://rancher.com/docs/k3s/latest/en/advanced/#:~:text=K3s%20is%20restarted.-,Auto%2DDeploying%20Manifests,-Any%20file%20found)
If you are experiencing this with you cluster, the fix is simple
remove the contents of `/var/lib/rancher/k3s/server/manifests` from each server (leave the manifest files in place).
This closes #51
=> Fix k3s manifest

roles/k3s/master/tasks/main.yml
The new step "Remove manifests and folders that are only needed for bootstrapping cluster so k3s doesn't auto apply on start" produces lots of log output which looks crowded if your terminal is not super-wide:
```
TASK [../k3s/roles/k3s/master : Remove manifests and folders that are only needed for bootstrapping cluster so k3s doesn't auto apply on start] ************************
Sunday 21 August 2022  13:25:38 +0200 (0:00:00.521)       0:00:35.185 ********* 
changed: [some-node] => (item={'path': '/var/lib/rancher/k3s/server/manifests/vip-rbac.yaml', 'mode': '0644', 'isdir': False, 'ischr': False, 'isblk': False, 'isreg': True, 'isfifo': False, 'islnk': False, 'issock': False, 'uid': 0, 'gid': 0, 'size': 805, 'inode': 1840852, 'dev': 26, 'nlink': 1, 'atime': 1661011790.3606591, 'mtime': …
```
=> Print fewer logs when removing manifests

.github/workflows/test.yml, vagrant/Vagrantfile, vagrant/test_cluster.py
- Sometimes errors might be introduced
- Example: #56 can be reproduced in the Vagrant cluster
- This pull request spins up the Vagrant cluster in CI, runs the `site` playbook and runs some basic tests against the cluster.
- Some tests are failing. From what I can tell, this is due to bugs in the cluster which need to be addressed. The tests work in my local cluster, though.
=> Execute Vagrant cluster in CI

collections/requirements.yml
[prereq role](https://github.com/techno-tim/k3s-ansible/blob/1ce3319087cafaff7889ba2b68f9dc0326815fa3/roles/prereq/tasks/main.yml#L8) use [selinux module](https://docs.ansible.com/ansible/latest/collections/ansible/posix/selinux_module.html) but module is not in requirements.yml.
=> add ansible.posix module to requirements.yml

inventory/sample/group_vars/all.yml, roles/k3s/master/tasks/main.yml, roles/k3s/master/templates/k3s.service.j2, roles/k3s/master/templates/metallb.crds.j2, roles/k3s/master/templates/vip.yaml.j2
- Enable the playbook to automatically determine if install has more than one host
- Based on host count decide to apply "CriticalAddonsOnly=true:NoExecute" to masters or not
- Main variable in variables file to allow it to be overwritten
- Should resolve node taint issues in #75
=> Fix master node taints in multi node installs

.github/download-boxes.sh
This fixes #105
- In case of grep not matching any line, it would return an error code and thus stop the script. This patch sets "present_boxes" to an empty value in case any of the commands fail.
=> Fix download-boxes.sh if no boxes are present

README.md
Add "collection" to the ansible-galaxy command as it will run without making changes if that collection argument is not provided.
With collection argument:
`ansible-galaxy collection install -r ./collections/requirements.yml
Process install dependency map
Starting collection install process
Installing 'ansible.utils:2.6.1' to '/home/user/.ansible/collections/ansible_collections/ansible/utils'
Installing 'community.general:5.6.0' to '/home/user/.ansible/collections/ansible_collections/community/general'
Installing 'ansible.posix:1.4.0' to '/home/user/.ansible/collections/ansible_collections/ansible/posix'
Installing 'kubernetes.core:2.3.2' to '/home/user/.ansible/collections/ansible_collections/kubernetes/core'`
Without collection argument:
`ansible-galaxy install -r …
=> Add "collection" to the ansible-galaxy command 

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/lint.yml, .pre-commit-config.yaml, requirements.txt
- Added [Pre-commit](https://github.com/pre-commit) to the project
- Added yamllint, ansible-lint, shellcheck and requirements.txt sorter
- Updated the PULL_REQUEST_TEMPLATE to ask about pre-commit
- Updated GitHub Actions lint job to run pre-commit 
I would've removed the GitHub Action lint job altogether in favor of [pre-commit.ci](http://pre-commit.ci/) but there is a bug there where ansible galaxy fails to install the requirements.yml [here](https://results.pre-commit.ci/run/github/555747600/1666428009.sf2LdDhNRR-Nb0UyfMk9yQ)
I did not run all the checks because these are minor changes that do not affect the current k3s setup and I'm on my laptop in at the university now. If someone wants to volunteer and try to run the `site.yml` and `reset.yml` would be cool. The molecule tests are …
=> Pre-commit hooks

roles/k3s/master/tasks/main.yml
new ansible version causes error 
```
msg: 'Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: creates, removes, strip_empty_ends, chdir, _uses_shell, _raw_params, stdin_add_newline, argv, stdin, executable.'
```
- This change simple removed the "warn" arg to avoid the fata error from ansible.
- Some autoformat indentation and extra space removed by vscode.
=> "command" module no longer supports "warn" argument

ansible.cfg
When using the ansible playbook with the deprecation_warnings flag on I got this warning:
```
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names to new standard, use
callbacks_enabled instead. This feature will be removed from ansible-core in version 2.15.
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```
This is the replacement for callback_whitelist
=> fix: config warning callback_whitelist

reboot.yml, reset.yml, roles/k3s/master/defaults/main.yml, roles/k3s/master/tasks/main.yml, roles/k3s/post/tasks/metallb.yml, site.yml
Instead of reading `ansible_user` (which may or may not be defined), this patch lets the roles rely on [Ansible facts](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_vars_facts.html).
=> Do not rely on ansible_user

inventory/sample/group_vars/all.yml, inventory/sample/hosts.ini, roles/lxc/handlers/main.yml, roles/lxc/tasks/main.yml, roles/proxmox_lxc/handlers/main.yml, roles/proxmox_lxc/tasks/main.yml, scripts/rc.local, site.yml
- adds support for using lxc containers as your kubernetes hosts
- https://gist.github.com/triangletodd/02f595cd4c0dc9aac5f7763ca2264185
=> add support for proxmox lxc containers

roles/k3s/master/tasks/metallb.yml
This patch removes duplicated code and cleans up Ansible log lines a bit.
=> Simplify download and patching of MetalLB manifests

.github/workflows/test.yml, molecule/ipv6/overrides.yml, roles/k3s/master/defaults/main.yml, roles/k3s/master/templates/vip.yaml.j2
- Currently, it is not possible to use multiple control nodes where the network interfaces to use have different names. This is due to the fact that `{{ flannel_iface }}` of the first control node will be hardcoded into the kube-vip manifest as the interface that all kube-vip pods must use.
- kube-vip is able to pick a matching interface per pod automatically for a ["long time"](https://github.com/kube-vip/kube-vip/issues/273#issuecomment-1310337093).
- This patch enables the automatic choice of interface by default and offers users the ability to override the interface if they want to (independently of `flannel_iface`, as requested in #221.
=> Pick kube-vip interface automatically by default

molecule/ipv6/host_vars/control2.yml, molecule/ipv6/molecule.yml, roles/k3s/master/defaults/main.yml
In its current form, the playbook cannot manage dual-stack multi-master clusters. The reason for this is every master other than the first get a URL parameter which includes `k3s_node_ip` of the first master verbatim. Since `k3s_node_ip` contains multiple, comma-separated IP addresses in dual-stack clusters, we need to extract a single IP address here.
=> Fix dual-stack clusters with multiple master nodes

inventory/sample/group_vars/all.yml
```yaml
kube_vip_tag_version: "v0.5.11"
metal_lb_speaker_tag_version: "v0.13.9"
metal_lb_controller_tag_version: "v0.13.9"
```
=> Chore: Update kube vip and MetalLB

roles/reset/tasks/main.yml
var registered for rc.local check is rcfile but under when it said rclocal which was undefined. changed to rcfile to correct.
-
-
-
=> (fix): correct var

inventory/sample/group_vars/all.yml
Bump k3s version from v1.24.11+k3s1 to v1.24.12+k3s1
=> Bump k3s version to v1.24.12+k3s1

.github/workflows/lint.yml, .github/workflows/test.yml, README.md
- Updated python to `3.11` for CI (same as freeze file)
- Fixed links in docs
=> Fix CI - python version

roles/k3s/node/defaults/main.yml, roles/k3s_agent/templates/k3s.service.j2, roles/k3s_server/defaults/main.yml, roles/k3s_server/tasks/main.yml, roles/k3s_server/tasks/metallb.yml, roles/k3s_server/tasks/vip.yml, roles/k3s_server_post/defaults/main.yml, roles/k3s_server_post/tasks/metallb.yml
For improved flexibility and maintainability.
* Update tasks in node role to use 'group_name_master' variable instead of hardcoded 'master' group name
* Update tasks in master role to use 'group_name_master' variable instead of hardcoded 'master' group name
* Update tasks in post role to use 'group_name_master' variable instead of hardcoded 'master' group name
=> Replace hardcoded 'master' group name with 'group_name_master' variable

roles/prereq/defaults/main.yml, roles/prereq/tasks/main.yml
Expanded the prereq role's secure_path task with support for Suse.
Added a default var (secure_path) for that task too, with separate values for RedHat and Suse.
(Didn't want to override Suse's default path order, nor RedHat's, I'm sure someone smarter than me decided on those orders for a reason)
Tested both site and reset.yml.
(Everything worked perfectly for openSUSE Leap 15.5 and SLES 15 SP5)
=> Expand secure_path with support for Suse

inventory/sample/group_vars/all.yml, roles/k3s_custom_registries/defaults/main.yml, roles/k3s_custom_registries/tasks/main.yml, site.yml
Added support for custom, private registries in k3s, according to [their documentation.](https://docs.k3s.io/installation/private-registry)
(Got inspired after getting rate limited by docker hub at work..)
As I've documented in the `sample/all.yml` comments, it could be useful if you're getting rate limited (for example by running your CI/CD jobs over and over in your cluster), or you're in an air-gapped environment where you don't have Internet access after the initial setup, or if you're bandwidth limited.
If you've set up a private registry (for example using Sonatype Nexus, or Docker's Registry image, or Harbor),
to act as a "pull-through cache" as docker calls it, you can specify and override those docker.io / quay.io / ghcr.io endpoints with your own in …
=> Add option for custom registries / mirrors

inventory/sample/group_vars/all.yml, roles/k3s_agent/tasks/http_proxy.yml, roles/k3s_agent/tasks/main.yml, roles/k3s_agent/templates/http_proxy.conf.j2, roles/k3s_server/tasks/http_proxy.yml, roles/k3s_server/tasks/main.yml, roles/k3s_server/templates/http_proxy.conf.j2, roles/reset/tasks/main.yml, site.yml
Added the option to install from behind an http proxy.
If configured (false by default), it puts your `http_proxy` + `https_proxy` + `no_proxy` env vars into a `k3s(-agent).service.d/http_proxy.conf` file, before anything gets installed.
This way k3s can access the internet for images etc through the proxy.
Also added env vars to the playbooks, defaulted to '', so ansible can still download the binaries and manifests even if you're behind a proxy.
In the reset main.yml I thought I'd add a conditional task.
So it doesn't try to remove the http_proxy files and errors out when you don't have them enabled/installed.
(I've ran and re-ran the checks a bunch of times on my fork, not sure what's up with the hosted runners.
The majority of the time it failed with the gurumeditation state error and …
=> Add option for install behind http_proxy

.yamllint, molecule/default/prepare.yml, molecule/resources/verify_from_outside/tasks/test/deploy-example.yml, reboot.yml, reset.yml, roles/k3s_agent/tasks/main.yml, roles/k3s_server/tasks/main.yml, roles/prereq/tasks/main.yml, roles/raspberrypi/tasks/setup/Rocky.yml, roles/raspberrypi/tasks/setup/Ubuntu.yml, roles/reset/tasks/main.yml, site.yml
I found issue #204 , the yes/no values bugged me a tiny bit too, thought I'd clear them out.
=> Update truthy values to true/false only, #204

.github/workflows/test.yml
Cleanup all artifacts, side effects, and actions since nodes are not ephemeral
- This is the cause of CI sometimes failing on self-hosted runners.  Unfortunately the self hosted runners are not ephemeral nodes (and yet another reason GitHub actions should be containers!).  Because they aren't and I don't have the sophistication that GitHub has with Azure, we need to clean up some of the side effects from our CI.  This PR does that.
=> fix(molecule): Cleanup all artifacts, side effects, and actions since nodes are not ephemeral

.github/workflows/ci.yml
- this closes #429 
- there's no point of running CI after a merge since we don't deploy
- this causes builds to queue up for no reason
- this should disable it
=> fix(ci): only run CI for PRs

.gitignore, site.yml
This PR adds a final step to the site.yml playbook, downloading the ~/.kube/config file from the first master to kubekonfig in the playbook directory.
This way you can `export KUBECONFIG=${PWD}/kubeconfig`, and deploy, reset, deploy, reset, deploy... and never worry about having the right kubeconfig.
I deliberately placed this task in the playbook, it shouldn't be part of a (reusable) role.
=> fetch kubeconfig from master after deployment

.github/workflows/test.yml, inventory/sample/group_vars/all.yml, molecule/README.md, molecule/cilium/molecule.yml, molecule/cilium/overrides.yml, roles/k3s_server/tasks/main.yml, roles/k3s_server_post/tasks/cilium.yml, roles/k3s_server_post/tasks/main.yml, roles/k3s_server_post/templates/calico.crs.j2, roles/k3s_server_post/templates/cilium.crs.j2
- Adds [Cilium CNI](https://cilium.io/get-started/) initialization option
- Disabled by default unless `cilium_iface` is defined, overrides flannel and calico
- Default settings assume nodes on same subnet and leverage [native routing](https://docs.cilium.io/en/stable/network/concepts/routing/#native-routing) with auto direct routes, [kube-proxy replacement](https://docs.cilium.io/en/latest/network/kubernetes/kubeproxy-free/), [BPF masquerade](https://docs.cilium.io/en/stable/network/concepts/masquerading/), [hybrid DSR](https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#dsr-mode), and [maglev LB algorithm](https://cilium.io/blog/2020/11/10/cilium-19/#maglev)
- [Routed mode](https://docs.cilium.io/en/stable/network/concepts/routing/) available for environments requiring …
=> Add Cilium CNI option

roles/k3s_server_post/tasks/cilium.yml
There is no need to use kube-vip LB for this Cilium config, k3s has an API server proxy listening in `127.0.0.1:6444` on all nodes in the cluster. I run with this setup in the https://github.com/onedr0p/cluster-template so just sharing some knowledge to here.
=> fix(cilium): k3s has an API server proxy at `127.0.0.1:6444`

roles/k3s_agent/tasks/http_proxy.yml, roles/k3s_agent/tasks/main.yml, roles/k3s_agent/templates/k3s.service.j2
Huge fan of this project, thanks for creating and maintaining it!
I'm happy to submit another PR to implement PXE boot support for the server role, 
but wanted to make sure there was interest in the existing work I've done first.
- Introduced enhancements to the `k3s_agent` role to address a specific issue encountered while setting up a Raspberry Pi 4 for PXE booting. This includes adding checks for PXE-boot conditions and modifying the `k3s.service.j2` template to dynamically set the `native` snapshotter, resolving issues related to "overlayfs" snapshotter incompatibilities in such setups.
- Improved overall maintainability and readability of the `k3s_agent` role by adopting idiomatic Ansible practices. This involved restructuring tasks into logical blocks, implementing conditional task …
=> Add PXE boot support to k3s_agent role

site.yml
Added a pre_task to site.yml to verify the minimum version of Ansible (2.11). 
Note: playbook syntax requires a non-empty "hosts" line, but the version check happens in the local machine (not the hosts in the host.ini).
-
-
-
=> Added pre_task to verify minimum Ansible version

roles/raspberrypi/tasks/setup/Raspbian.yml
When replacing a node, I noticed that the cgroups task has an old path. Old Raspbian had `/boot/cmdline.txt`, but that file has been moved to `/boot/firmware/cmdline.txt`. Upon updating that path, configuration completed successfully and k3s service started without error. When I originally built the cluster, I made that change manually. Replacing a node and using the playbook exposed this issue.
- https://forums.raspberrypi.com/viewtopic.php?t=365886
- https://forums.raspberrypi.com/viewtopic.php?p=2186916
=> Fix cgroups cmdline path

roles/k3s_server_post/tasks/cilium.yml
This PR addresses the issue if the install user's home directory is not in `/home/username`. The `Copy config file to user home directory` task copies `/etc/rancher/k3s/k3s.yaml` to `"{{ ansible_user_dir }}/.kube/config"`
Without this change, when installing Cilium by a non-standard user, it will fail to set the `KUBECONFIG` correctly and the cilium installer will fail to fetch the k8s/k3s version with an error as described in https://github.com/techno-tim/k3s-ansible/issues/446.
- This ensures the `KUBECONFIG` environment variable points to the user's directory and does not assume it is in `/home/username/.kube/config`
=> Cilium Install - Ensure KUBECONFIG points to install users home directory

inventory/sample/group_vars/all.yml, reboot.yml, reset.yml, roles/lxc/handlers/main.yml, roles/raspberrypi/handlers/main.yml
This change adds an optional `custom_reboot_command`. On Diet Pi, there is no dbus installed. See [Diet Pi Release Notes](https://dietpi.com/docs/releases/v8_22/#bug-fixes).
> DietPi ships without dbus and with logind masked by default, as we do not see their features being used on a typical DietPi system. Instead, dbus is installed and logind unmasked on demand on certain software installs or when chosen via dietpi.txt. However, the newer systemd version since Bookworm attempts dbus > logind communication in any case when calling poweroff/reboot/halt, despite no wall message being sent, e.g. to handle shutdown inhibitors (like open SSH session being able to prevent shutdown), and throws errors if either dbus is not reachable or logind not running. Until in case dbus or logind are further …
=> Support defining a custom reboot command

README.md
Instructions were unclear on how to have the Kube config copied. As a noob, I spent a considerable amount of time figuring out where the config file was and why the proposed `scp debian@master_ip:~/.kube/config ~/.kube/config` was giving me no such file error. So, I thought I would help the next home labber by including these updated instructions.
- Updated to include the new location for kube config
- Added possible errors and how to overcome them
- Steps to do after copying the config
I acknowledge that I might be an edge case where the .kube/config file was not deployed in the proper place, but in case this is the new design the PR is here to help out!
Since it is just documentation I will not rerun the site.yml as it is picky!
=> Update Kube Config instructions

.github/workflows/test.yml
- disabling ipv6 tests per https://github.com/techno-tim/k3s-ansible/issues/475
- would love to enable them again in the future
=> fix(molecule): Disable ipv6 test

roles/k3s_server_post/templates/cilium.crs.j2
The current implementation  of `cilium_bgp_lb_cidr` does not allow allow for an IP range to be provided.
This PR uses the same syntax as `kube_vip_lb_ip_range` and `metal_lb_ip_range` to achieve the same.
=> Allow IP range for `cilium_bgp_lb_cidr`

roles/k3s_server/tasks/main.yml, roles/k3s_server_post/tasks/main.yml
Adjusted the when: for calling metallb.yml in both k3s_server and k3s_server_post roles as to not fail in undefined var checks.
=> fixed broken when statement for metallb optional tasks

.github/workflows/lint.yml, inventory/sample/group_vars/all.yml, requirements.txt, roles/k3s_server/tasks/main.yml, roles/k3s_server_post/tasks/main.yml, roles/k3s_server_post/tasks/metallb.yml
updated k8s components, added fix for metalb, updated actions
```yaml
k3s_version: v1.30.1+k3s1
calico_tag: "v3.28.0" 
cilium_tag: "v1.15.6" 
kube_vip_tag_version: "v0.8.0"
metal_lb_speaker_tag_version: "v0.14.5"
metal_lb_controller_tag_version: "v0.14.5"
```
=> chore(deps): Updated all k8s components

roles/k3s_server/defaults/main.yml, roles/k3s_server/templates/vip.yaml.j2
With the kube_vip_arp parameter it is possible to set or unset the vip_arp environment variable of the kube-vip-ds daemonset. The value of the kube_vip_arp is true by default to not change the existing default.
=> k3s_server: add kube_vip_arp parameter

roles/download/meta/main.yml, roles/k3s_agent/defaults/main.yml, roles/k3s_agent/meta/main.yml, roles/k3s_agent/templates/k3s.service.j2, roles/k3s_custom_registries/defaults/main.yml, roles/k3s_custom_registries/meta/main.yml, roles/k3s_server/defaults/main.yml, roles/k3s_server/meta/main.yml, roles/k3s_server/tasks/http_proxy.yml, roles/k3s_server/tasks/main.yml, roles/k3s_server_post/defaults/main.yml, roles/k3s_server_post/meta/main.yml, roles/k3s_server_post/tasks/cilium.yml, roles/k3s_server_post/templates/calico.crs.j2, roles/lxc/meta/main.yml, roles/prereq/defaults/main.yml, roles/prereq/meta/main.yml, roles/reset/defaults/main.yml, roles/reset/meta/main.yml
- Add default values to roles to refrain from missing values in the `all.yml` file.
- Allow modular use of roles when consumed as a collection.
- Add metadata to all roles with documented arguments.
=> ➕ Add default values to roles

roles/k3s_server/tasks/main.yml
If k3s_create_kubectl_symlink is set to false the kubectl symlink will not be created.
If k3s_create_crictl_symlink is set to false the crictl symlink will not be created.
By default the symlinks will be created. The default behavior is not changed.
=> Make it possible to disable the creation of the kubectl/crictl symlinks

inventory/sample/group_vars/all.yml, roles/k3s_server/defaults/main.yml, roles/k3s_server/meta/main.yml, roles/k3s_server/templates/vip.yaml.j2
With the kube_vip_bgp parameter it is possible to enable the kube-vip BGP support (https://kube-vip.io/docs/modes/bgp/).
The configuration is possible with the following new parameters:
* kube_vip_bgp_routerid
* kube_vip_bgp_as
* kube_vip_bgp_peeraddress
* kube_vip_bgp_peeras
=> k3s_server: add kube-vip BGP support

roles/k3s_server/meta/main.yml
The commit 3a20500f9c4b2d160bf7fce127ab91850851dec6 has introduced argument specs in the role meta information. These two parameters were still missing there.
Realted to 2d0596209ee542d728830d4f9e97686ac1c28f26
=> k3s_server: add missing parameter descriptions

roles/k3s_server/defaults/main.yml, roles/k3s_server/tasks/main.yml, roles/k3s_server_post/defaults/main.yml, roles/k3s_server_post/tasks/calico.yml, roles/k3s_server_post/tasks/cilium.yml, roles/k3s_server_post/tasks/metallb.yml
Closes techno-tim/k3s-ansible#566
=> Make kubectl binary configurable with the k3s_kubectl_binary parameter

roles/raspberrypi/tasks/setup/Ubuntu.yml, roles/raspberrypi/tasks/teardown/Ubuntu.yml
This package does not exist anymore on Ubuntu 24 and is integrated into the kernel, so we don't need an alternative.
See also
- https://packages.ubuntu.com/search?keywords=linux-modules-extra-raspi&searchon=names 
- https://github.com/k3s-io/k3s-ansible/pull/346
=> fix: fix raspberry pi preparation for ubuntu 24.04

roles/k3s_server_post/defaults/main.yml, roles/k3s_server_post/meta/main.yml, roles/k3s_server_post/tasks/cilium.yml, roles/k3s_server_post/templates/cilium.crs.j2
With the cilium_bgp_neighbors parameter it is possible to define
multiple BGP peer ASN & address pairs for Cilium.
Sample:
```
cilium_bgp_neighbors:
- peer_address: 192.168.128.10
peer_asn: 64512
- peer_address: 192.168.128.11
peer_asn: 64512
- peer_address: 192.168.128.12
peer_asn: 64512
```
It is possible to merge further lists with cilium_bgp_neighbors__*
parameters.
Sample:
```
cilium_bgp_neighbors__extra:
- peer_address: 192.168.128.10
peer_asn: 64512
cilium_bgp_neighbors:
- peer_address: 192.168.128.11
peer_asn: 64512
- peer_address: 192.168.128.12
peer_asn: 64512
```
This will result in the following list of BGP peer ASN & address pairs:
```
- peer_address: 192.168.128.10
peer_asn: 64512
- peer_address: 192.168.128.11
peer_asn: 64512
- peer_address: 192.168.128.12
peer_asn: 64512 …
```
=> k3s_server_post: add cilium_bgp_neighbors parameter

roles/k3s_server/defaults/main.yml, roles/k3s_server/meta/main.yml, roles/k3s_server/tasks/vip.yml, roles/k3s_server/templates/vip.yaml.j2
With the kube_vip_bgp_peers it is possible to define multiple BGP peer ASN & address pairs for kube-vip.
Sample:
```
kube_vip_bgp_peers:
- peer_address: 192.168.128.10
peer_asn: 64512
- peer_address: 192.168.128.11
peer_asn: 64512
- peer_address: 192.168.128.12
peer_asn: 64512
```
It is possible to merge further lists with kube_vip_bgp_peers__* parameters.
Sample:
```
kube_vip_bgp_peers__extra:
- peer_address: 192.168.128.10
peer_asn: 64512
kube_vip_bgp_peers:
- peer_address: 192.168.128.11
peer_asn: 64512
- peer_address: 192.168.128.12
peer_asn: 64512
```
This will result in the following list of BGP peer ASN & address pairs:
```
- peer_address: 192.168.128.10
peer_asn: 64512
- peer_address: 192.168.128.11
peer_asn: 64512
- peer_address: 192.168.128.12
peer_asn: 64512
```
=> k3s_server: add kube_vip_bgp_peers parameter

README.md, roles/k3s_agent/meta/main.yml, roles/k3s_server/meta/main.yml, roles/lxc/meta/main.yml, roles/proxmox_lxc/meta/main.yml, roles/raspberrypi/meta/main.yml, roles/reset_proxmox_lxc/meta/main.yml
- Add variable documentation. 
Closes #560
=> Variable documentation
