README.md, deploy.sh, kill-all.sh
update the inventory path in readme and added a couple bash scripts to ease entering ansible-playbook command
=> inventory path + couple bash scripts

.github/PULL_REQUEST_TEMPLATE.md, README.md, deploy.sh, kill-all.sh, reset.sh
updates to readme to make it a little more approachable
=> Readme updates

inventory/sample/group_vars/all.yml, roles/k3s/master/templates/metallb.crds.j2, vagrant/Vagrantfile
- upgrade k3s to v1.24.4+k3s1
-upgrade metallb to 0.13.5
=> upgrade k3s to v1.24.4+k3s1

roles/k3s/post/tasks/main.yml
=> fix(ansible): Fix group permissions on tmp folder

.github/workflows/test.yml, molecule/README.md, molecule/default/molecule.yml, molecule/resources/converge.yml, molecule/resources/reset.yml, molecule/resources/verify/from_outside/tasks/test/get-nodes.yml, molecule/single_node/molecule.yml, molecule/single_node/overrides.yml
- Test a cluster consisting of one single node using molecule
- related to #75 
- creates some (trivial) merge conflicts with #48
=> Test single-node cluster

README.md
=> chore(docs): Updated with ansible utils

.github/workflows/test.yml
- closes https://github.com/techno-tim/k3s-ansible/issues/90
=> fix(github): ignore readme updates

.github/workflows/lint.yml, molecule/resources/verify/from_outside/tasks/test/deploy-example.yml, molecule/resources/verify/from_outside/tasks/test/get-nodes.yml, requirements.txt, roles/k3s/master/tasks/main.yml, roles/k3s/post/defaults/main.yml
=> CI: Fix linting job for ansible-lint 6.6.0

reset.yml
see https://github.com/techno-tim/k3s-ansible/pull/92#discussion_r979367257
=> Fix role order in reset playbook

.github/workflows/test.yml
Makes things prettier and easier to inspect.
=> adds colors to molecule testing in GitHub action

.github/workflows/lint.yml, .github/workflows/test.yml
=> feat(ci): switching to self-hosted runners

.github/workflows/lint.yml, .github/workflows/test.yml
Reverts techno-tim/k3s-ansible#133
This was a test
=> Revert "feat(ci): switching to self-hosted runners"

.github/workflows/lint.yml, .github/workflows/test.yml
- pin actions
- cache pip & more
- add pin check for actions
=> GitHub Actions Fixes

ansible.cfg
- Add yaml stdout for better readability in the cli
- Optimize ssh connections
- Move become to correct section per ansible docs
- Add log path for better TSing
- This will make it so that the error is able to be copied and pasted into Discord, Issue request
- Full log can be uploaded to the issues section
-  General formatting for better readability of the file
=> chore: :zap: Multiple configuration changes

README.md
=> docs(README): Updated readme with fixes and context

inventory/sample/group_vars/all.yml
- updated `kube-vip` to `0.5.6`
=> chore(dependencies): updated kube-vip to 0.5.6

.github/workflows/lint.yml, .github/workflows/test.yml, inventory/sample/group_vars/all.yml
- `kube_vip_tag_version: "v0.5.7"`
- `k3s_version: v1.24.8+k3s1`
- updates github actions
=> K3s 1 24 8

inventory/sample/group_vars/all.yml
=> feat(k3s): Updated to v1.24.9+k3s1

roles/raspberrypi/handlers/main.yml
- this fixes https://github.com/techno-tim/k3s-ansible/issues/199
=> fix(raspberrypi): Fix handler name

inventory/sample/group_vars/all.yml
- updated k3s to `v1.24.10+k3s1`
=> feat(k3s): Updated to v1.24.10+k3s1

README.md
- Removed note about ansible version
=> docs(README): Removed note about ansible version

inventory/sample/group_vars/all.yml
- updated k3s to [v1.24.11+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.24.11%2Bk3s1)
=> feat(k3s): Updated to v1.24.11+k3s1

inventory/sample/group_vars/all.yml
- Remove unused variable metal_lb_frr_tag_version
=> Remove unused variable metal_lb_frr_tag_version

inventory/sample/group_vars/all.yml
- updated k3s to `v1.25.16+k3s4`
=> feat(k3s): Updated to v1.25.16+k3s4

.github/dependabot.yml
- added dependabot support for github actions
- added dependabot support for docker
=> feat(dependabot): Added docker docker and github actions

inventory/sample/group_vars/all.yml
=> feat(k3s): Updated to v1.29

inventory/sample/group_vars/all.yml
- `kube_vip_tag_version: "v0.6.4"`
- `metal_lb_speaker_tag_version: "v0.13.12"`
- `metal_lb_controller_tag_version: "v0.13.12"`
=> chore(deps) Updated LBs

.github/workflows/ci.yml
- Do not run CI for files that' aren't checked
=> fix(ci): Don't run CI for certain files

.ansible-lint, .github/workflows/cache.yml, .github/workflows/lint.yml, .github/workflows/test.yml, .pre-commit-config.yaml
- updated `pre-commit`
- cleaned up actions comments
-
=> chore(deps) pre-commit updates

inventory/sample/group_vars/all.yml, roles/k3s_server/tasks/vip.yml
- `calico_tag: "v3.27.2"`
- `cilium_tag: "v1.15.1"`
- `kube_vip_tag_version: "v0.7.1"`
- `metal_lb_speaker_tag_version: "v0.14.3"`
- `metal_lb_controller_tag_version: "v0.14.3"`
=> chore(deps): Updated

inventory/sample/group_vars/all.yml
=> chore(deps): Updated kube-vip

inventory/sample/group_vars/all.yml
=> feat(k3s): Updated to v1.29.2+k3s1

inventory/sample/group_vars/all.yml, roles/k3s_server_post/tasks/calico.yml, roles/k3s_server_post/tasks/cilium.yml
=> chore(deps): Updated cilium to v1.15.2

.python-version, roles/k3s_server_post/tasks/metallb.yml
=> Metallb 0.14.4 support

roles/k3s_server_post/tasks/cilium.yml
Related to eddbcbfb7613913cd2dd180f5cef89fbd016b563
=> k3s_server_post: always set _cilium_bgp_neighbors
